Settings stuff to accept multiple code; Exporter query update
monsieurbiz/SyliusColishipPlugin pull request #12
Opened 2021-07-14 07:33 UTC by ehibes

#11

2021-07-19 12:54 UTC, maximehuran requested changes

2021-07-19 12:54 UTC, maximehuran commented on src/Directory/ShippingMethodCodeDirectory.php
> +            $values[$method->getCode()] = $method->getCode();
I don't agree with this change because we want to display the name and not the code in the settings form

2021-07-19 14:23 UTC, maximehuran approved these changes

2021-07-20 14:14 UTC, jacquesbh approved these changes

2021-07-20 14:14 UTC, merged

2021-07-20 14:14 UTC, jacquesbh commented
Thank you @ehibes ! 🎉