Allow Sylius 1.11
monsieurbiz/SyliusColishipPlugin pull request #22
Opened 2022-09-11 16:13 UTC by jacquesbh

- Add a name to each test in github actions
- Let's go for Sylius 1.11 🔥

2022-09-12 07:37 UTC, lanfisis requested changes
There's a lot on error with the CI, is it normal ?

2022-09-14 08:07 UTC, delyriand requested changes

2022-09-20 18:54 UTC, jacquesbh commented on .github/workflows/recipe.yaml
> +        php: ["7.4" ,"8.0"]
Yes.
The recipe action forces the version of sylius during installation.
And tests don't.

2022-09-21 06:38 UTC, delyriand approved these changes

2022-09-21 07:32 UTC, etienne-monsieurbiz approved these changes

2022-09-21 07:45 UTC, merged